---
dist: bionic
sudo: required
language: python
python:
  - "2.7"
cache: pip

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt update -qq
  - sudo apt -y -o Dpkg::Options::="--force-confnew" install docker-ce

install:
  - sudo pip install ansible ansible-lint docker-py
  - ansible --version

script:
  - echo "[local]\nlocalhost ansible_connection=local" > /etc/ansible/hosts
  - ansible-playbook -v -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -v -i tests/inventory tests/test.yml -vvvv

after_script:
  - docker ps -a

email:
  - linuxmalaysia@gmail.com
