---
matrix:
  include:
    - name: "Ubuntu Bionic Test"
      os: linux
      dist: bionic
      env: TOXENV=ubuntu
    - name: "Ubuntu Xenial Test"
      os: linux
      dist: xenial
      env: TOXENV=ubuntu
    - name: "Centos 7.x Test"
      os: linux
      dist: bionic
      # This to call docker for centos7
      env: TOXENV=centos7
    - name: "Debian Stretch Test"
      os: linux
      dist: bionic
      # This to call docker for stretch
      env: TOXENV=stretch

sudo: required
language: python
python:
  - "2.7"
cache: pip

services:
  - docker

before_install:
  - df -h
  - free -m
  - uname -a
  - uptime
  - dmesg
  - tests/b4install.sh

install:
  - tests/install.sh

script:
  - tests/scripttest.sh

after_script:
  - docker ps -a

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
 
email:
  - linuxmalaysia@gmail.com

# https://www.ansible.com/blog/testing-ansible-roles-with-docker
