---
matrix:
  include:
    - name: "Ubuntu Bionic Test"
      os: linux
      dist: bionic
      env: TOXENV=ubuntu
    - name: "Ubuntu Xenial Test"
      os: linux
      dist: xenial
      env: TOXENV=ubuntu

sudo: required
language: python
python:
  - "2.7"
cache: pip

services:
  - docker

before_install:
  - tests/b4install.sh

install:
  - tests/install.sh

script:
  - echo "[default]\nhost_key_checking = False" > ansible.cfg
  - echo "[default]\nansible_ssh_common_args='-o StrictHostKeyChecking=no'\n" >> ansible.cfg
  - echo "[local]\nlocalhost ansible_connection=local" >> ansible.cfg
  - export ANSIBLE_HOST_KEY_CHECKING=False
  - ansible-playbook -v -i tests/inventory tests/test.yml --syntax-check
  - ansible-playbook -e 'host_key_checking=False' -i tests/inventory tests/test.yml -vvvv --connection=local
# Run the role/playbook again, checking to make sure it's idempotent. We only check for failed. Report out alway change.
  - >
    ansible-playbook -e 'host_key_checking=False' -i tests/inventory tests/test.yml --connection=local
    | grep -q 'failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)

after_script:
  - docker ps -a

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
 
email:
  - linuxmalaysia@gmail.com

# https://www.ansible.com/blog/testing-ansible-roles-with-docker
