---
sudo: required

env:
#  - distro: centos7
#    init: /usr/lib/systemd/systemd
#    run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
#    version: latest

#  - distribution: ubuntu
#    version: xenial

  - distribution: ubuntu
    version: bionic

services:
  - docker

before_install:
  - 'sudo docker pull ${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible travis'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/lynis_ansible:ro ${distribution}-${version}:ansible > "${container_id}"'

  - 'sudo docker rm -f "$(cat ${container_id})"'
