---
- name: Install Lynis Repository
  block:
    - name: Add Public Key
      apt_key:
        url: https://packages.cisofy.com/keys/cisofy-software-public.key
        state: present
      when:
        ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

    - name: Install Lynis Repo
      apt_repository:
        repo: deb https://packages.cisofy.com/community/lynis/deb/ stable main
        state: present
        filename: cisofy-lynis
      when:
        ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

- name: Lynis | Install Lynis from apt
  apt:
    name=lynis
    state=present
    force=no
    install_recommends=no
    update_cache=yes
  register: lynis_isinstalled
  tags: lynis
  when:
    ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu'

- name: Creates a cron file under /etc/cron.d
  when: lynis_audit_system_linux is defined
  cron:
    name: Lynis | Add Lynis to cron.d
    minute: "{{ 59 | random }}"
    hour: "{{ 4 | random }}"
    user: root
    job: "lynis audit system --quick --pentest -c"
    cron_file: lynis
  tags: lynis
