---
# Include variables and define needed variables.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Lynis | Install Lynis (Debian | Ubuntu)
  include: debian.yml
  when:
    (ansible_os_family == 'Debian' or ansible_os_family == 'Ubuntu') and
    (lynis_use_packages is defined and lynis_use_packages)
  tags: lynis

- name: Lynis | Install Lynis (CentOS | RHEL)
  include: rhel.yml
  when:
    (ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat') and
    (lynis_use_packages is defined and lynis_use_packages)
  tags: lynis

- name: Lynis | Install Lynis manually (OS-independent)
  include: manual.yml
  when: lynis_use_packages is defined and not lynis_use_packages
  tags: lynis

### lynis_audit_system 09122018 auditlinux.yml

- name: Lynis | Run Lynis for Linux
  include: runauditlinux.yml
  when: lynis_audit_system_linux is defined and lynis_audit_system_linux
  tags: lynis
