---
- name: Lynis | Yum Add repositories
  yum_repository:
    name: lynis
    description: Lynis RPM Repo
    file: lynis
    baseurl: https://packages.cisofy.com/community/lynis/rpm/
    gpgkey: https://packages.cisofy.com/keys/cisofy-software-rpms-public.key
    gpgcheck: yes
    enabled: yes
  when:
    ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat'
  tags: lynis

- name: Lynis | ensure a list of packages installed
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - ca-certificates
    - curl
    - nss
    - openssl
  when:
    ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat'
  tags: lynis

- name: Lynis | Install Lynis from yum
  yum:
    name: lynis
    state: present
    update_cache: yes
    disable_gpg_check: no
  register: lynis_isinstalled
  when:
    ansible_os_family == 'CentOS' or ansible_os_family == 'RedHat'
  tags: lynis

- name: Creates a cron file under /etc/cron.d
  when: lynis_audit_system_linux is defined
  cron:
    name: Lynis | Add Lynis to cron.d
    minute: "{{ 59 | random }}"
    hour: "{{ 4 | random }}"
    user: root
    job: "lynis audit system --quick --pentest --cronjob --nocolors"
    cron_file: lynis
  tags: lynis
