---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    ansible_connection_options:
      connection: local
lint:
  name: yamllint
platforms:
  - name: delegated-travis-instance
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    host_vars:
      delegated-travis-instance:
        ansible_connection: local
scenario:
  name: default
verifier:
  name: testinfra
  options:
    verbose: True
  lint:
    name: flake8
